logging:
    level:
        org:
            hibernate:
                SQL: debug
                stat: debug
                type: trace
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
server:
    port: 5001
spring:
    jpa:
        properties:
            hibernate:
                format_sql: false
                generate_statistics: false
        show-sql: false
