server:
  port: 5000

spring:
  main:
    banner-mode: 'on'
  profiles:
#    active: qa
    include: datasource-spanner,hibernate,logging

inheritance: false
e121: false
test: false
multCol: false
objectState: false
z2Tester: false
one2one: false
UnidirectionalOne2ManyTester: false
One2ManyTester: false
m2mTester: false
T2OTMTester: false
T1OTOTester: false
compositeKeys: true